# Default values for hzero-register.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.choerodon.com.cn/hzero-hzero/hzero-register
  pullPolicy: Always

deployment:
  managementPort: 8001

env:
  open:
    # 检索服务选项，注册中心不需要检索服务
    EUREKA_CLIENT_FETCH_REGISTRY: false
    # 注册中心将自己作为客户端来尝试注册自己，注册中心集群环境下需开启此配置
    EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
    # Eureka 注册中心地址
    EUREKA_DEFAULT_ZONE: http://dev.hzero.org:8000/eureka
    # 开启自我保护机制
    EUREKA_SERVER_ENABLE_SELF_PRESERVATION: false
    # 推荐 JVM 配置
    JAVA_OPTS: >
      -Xms1024m
      -Xmx1536m
metrics:
  path: /actuator/prometheus
  group: spring-boot

logs:
  parser: spring-boot

persistence:
  enabled: false
  ## A manually managed Persistent Volume and Claim
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  # existingClaim:
  # subPath:

service:
  enabled: false
  type: ClusterIP
  port: 8000

ingress:
  enabled: false

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 1.7Gi
  requests:
    # cpu: 100m
    memory: 1.2Gi

